services:
  cockroach:
    image: cockroachdb/cockroach:v24.3.4
    command: start-single-node --insecure --listen-addr=0.0.0.0:26257 --advertise-addr=localhost
    restart: unless-stopped
    ports:
      - "26257:26257"
      - "8080:8080"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
